### ISSUE TITLE
jpeg sample error

### ISSUE THREAD

**Issue by webinone** [3d0c/gmf#56]
Error opening codec 'jpeg2000:JPEG 2000', averror: Invalid argument

error code line

codeCtx.go : 200 line 

if averr := C.avcodec_open2(this.avCodecCtx, this.codec.avCodec, &avDict); averr < 0 {
		return errors.New(fmt.Sprintf("Error opening codec '%s:%s', averror: %s", this.codec.Name(), this.codec.LongName(), AvError(int(averr))))
	}

Help me

**Comment by 3d0c** [comment]
@webinone Looks like you don't have jpeg2000 codec, check it with `ffmpeg -codecs | grep -i jpeg`

**Comment by xuecai** [comment]
i have the same error

[root@php7 FFmpeg-n3.3]# /usr/local/ffmpeg/bin/ffmpeg -codecs | grep -i jpeg
ffmpeg version 3.3 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 4.8.3 (GCC) 20140911 (Red Hat 4.8.3-9)
  configuration: --prefix=/usr/local/ffmpeg --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' --enable-bzlib --disable-crystalhd --enable-gnutls --enable-ladspa --enable-libass --enable-libcdio --enable-libdc1394 --enable-libfdk-aac --enable-nonfree --enable-libfdk-aac --enable-nonfree --disable-indev=jack --enable-libfreetype --enable-libgsm --enable-libmp3lame --enable-openal --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libx264 --enable-libx265 --enable-libxvid --enable-avfilter --enable-avresample --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
98: DEVILS jpeg2000             JPEG 2000 (decoders: jpeg2000 libopenjpeg ) (encoders: jpeg2000 libopenjpeg )
99: DEVILS jpegls               JPEG-LS
104: .EVI.S ljpeg                Lossless JPEG
111: DEVIL. mjpeg                Motion JPEG (decoders: mjpeg mjpeg_cuvid )
112: D.VIL. mjpegb               Apple MJPEG-B
132: D.V.L. nuv                  NuppelVideo/RTJPEG
168: D.V... smvjpeg              Sigmatel Motion Video
170: D.VIL. sp5x                 Sunplus JPEG (SP5X)
269: D.A.L. adpcm_ima_smjpeg     ADPCM IMA Loki SDL MJPEG

[root@php7 FFmpeg-n3.3]# rpm -qa | grep jpeg
55:libjpeg-turbo-1.2.90-5.el7.x86_64
132:openjpeg-1.5.1-10.el7.x86_64
288:openjpeg-libs-1.5.1-10.el7.x86_64
346:openjpeg2-2.1.0-7.el7.x86_64
347:openjpeg2-devel-2.1.0-7.el7.x86_64
407:openjpeg-devel-1.5.1-10.el7.x86_64

**Comment by maurorappa** [comment]
Hi, I'm  getting the same error using your sample video:

2018/08/01 21:49:32 worker started
2018/08/01 21:49:32 worker started
2018/08/01 21:49:32 worker started
[jpeg2000 @ 0x7000000] The encoder timebase is not set.
[jpeg2000 @ 0x7800000] The encoder timebase is not set.
goroutine 10 [running]:
runtime/debug.Stack(0x43, 0xc4200f0000, 0x40cc4a0)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/debug/stack.go:16 +0x22
main.fatal(0x4103720, 0xc4200da050)
	/Users/maurorappa/Go/video-to-jpeg.go:18 +0x22
main.encodeWorker(0xc42007c060, 0xc420016070, 0xc42000c0c0)
	/Users/maurorappa/Go/video-to-jpeg.go:73 +0x417
created by main.main
	/Users/maurorappa/Go/video-to-jpeg.go:138 +0x272
[jpeg2000 @ 0x6027200] 2018/08/01 21:49:32 Error opening codec 'jpeg2000:JPEG 2000', averror: Invalid argument
The encoder timebase is not set.
2018/08/01 21:49:32 worker started
exit status 1

here some info of my setup:

go version go1.10.3 darwin/amd64

 ffmpeg -codecs | grep -i jpeg
ffmpeg version 4.0.2 Copyright (c) 2000-2018 the FFmpeg developers
  built with Apple LLVM version 9.0.0 (clang-900.0.39.2)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.0.2 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
 DEVILS jpeg2000             JPEG 2000
 DEVILS jpegls               JPEG-LS
 .EVI.S ljpeg                Lossless JPEG
 DEVIL. mjpeg                Motion JPEG
 D.VIL. mjpegb               Apple MJPEG-B
 D.V.L. nuv                  NuppelVideo/RTJPEG
 D.V... smvjpeg              Sigmatel Motion Video
 D.VIL. sp5x                 Sunplus JPEG (SP5X)
 D.A.L. adpcm_ima_smjpeg     ADPCM IMA Loki SDL MJPEG

it seems installed, what else can I check?

**Comment by maurorappa** [comment]
Great! it's working!
I'll raise a PR to update the example
